import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/layout/Navbar/Navbar";
import Background from "@/components/layout/Background/Background";
import Header from "@/components/layout/Header/Header";
import Loader from "@/components/layout/Loader/Loader";
import Footer from "@/components/layout/Footer/Footer";

const font = Cinzel({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Loader />
          <Background />
          <Navbar />
          <div className="container max-w-4xl mx-auto p-2 sm:p-4">
            <Header />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
